# Server config
server.port=8080

# Application configuration settings
app.name=Software Development Document Environment

# Document watcher poll directory (defaults to directory "input-documents" under current execution context)
app.poll.dir=input-documents

# Enable SMS and Email simulated authentication toggle
app.mfa.enabled=false
# Enable Approver notifications toggle
app.notifications.enabled=false

# Authentication Strategy: 'DB' or 'LDAP'
app.auth.strategy=DB

# Mock LDAP properties
app.ldap.url=ldap://localhost:389
app.ldap.base-dn=dc=cth,dc=com

# Database Connection Properties
# We use a memory database for H2 during standard profiles to prevent file locks or AUTO_SERVER issues.
spring.datasource.url=jdbc:h2:mem:sdmdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Enable H2 console for easy access
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Spring doc / Swagger path configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Multipart configuration to support large files
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
